openapi: 3.0.0
info:
    title: User Service API
    description:
    version: 0.0.0

servers:
    - url:
    description:

paths:
    /api/users:
        get:
            operationId: getUsers
            summary: Returns a list of users.
            description:
            responses:
                "200":
                    description: A JSON array of users
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                "400":
                    description:
                "404":
                    description:
                "500":
                    description:
                default:
                    description: Unexpected error
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type:
                                items:
                                    type:
    /api/users/{userID}:
        get:
            operationId: getUserById
            summary: Returns a user by ID
            description:
            parameters:
                - name: userId 
                    in: path
                    required: true
                    description: The ID of the user to return.
                    schema:
                        type: 
                        format:
                        minimum:
            responses:
                "200":
                    description: A user object.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type:
                                        format:
                                        example:
                                    name:
                                        type:
                                        example: test user
                "400":
                    description:
                "404":
                    description:
                default:
                    description: Unexpected error
        put:
            operationId: updateUser
            summary:
            description:
            parameters:
                - name: userId 
                    in: path
                    required: true
                    description: The ID of the user to update.
                    schema:
                        type:
                        format:
                        minimum:
            responses:
                "200":
                    description:
                "401":
                    description:
                "404":
                    description:
                default:
                    description: Unexpected error
        delete:
            operationId: deleteUser
            summary:
            description:
            parameters:
                - name: userId 
                    in: path
                    required: true
                    description: The ID of the user to delete.
                    schema:
                        type:
                        format:
                        minimum:
            responses:
                "200":
                    description:
                "401":
                    description:
                "404":
                    description:
                "500":
                    description:
                default:
                    description: Unexpected error
    /api/users/signup:
        post:
            operationId: addUser
            summary: Creates a user.
            description:
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type:
                            properties:
                                username:
                                    type:
            responses:
                "201":
                    description:
                "400":
                    description:
                "500":
                    description:
                default:
                    description:
    /api/users/login:
        post:
            operationId: userLogin
            summary: Login user.
            description:
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type:
                            properties:
                                email:
                                    type:
                                password:
                                    type:
            responses:
                "200":
                    description:
                "401":
                    description:

    /api/users/logout:
        get:
            operationId: userLogout
            summary: Logout user.
            description:
            requestHeader:
                required: true
                content:
                    header:
                        schema:
                            type:
                                properties:
                                    authorization:
                                        type:


            responses:
                "500":
                    description:
                default:
                    description:
                      
