openapi: 3.0.0
info:
    title: User Service API
    description:
    version: 0.0.0

servers:
    - url:
    description:

paths:
    /api/users:
        get:
            operationId: getAllUsers
            summary: Returns a list of users.
            description:
            responses:
                "200":
                    description: A JSON array of users
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        _id:
                                            type: String
                                        name:
                                            type: String
                                        address:
                                            type: String
                                          email:
                                            type: String
                "500":
                    description: Server error
                default:
                    description: Unexpected error

    /api/users/{userID}:
        get:
            operationId: getUserById
            summary: Returns a user by ID
            description:
            parameters:
                - name: userId 
                    in: path
                    required: true
                    description: The ID of the user to return.
                    schema:
                        type: 
                        format:
                        minimum:
            responses:
                "200":
                    description: A user object.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: String
                                        format:
                                        example:
                                    name:
                                        type: String
                                        example: test user
                "400":
                    description:
                "404":
                    description:
                default:
                    description: Unexpected error
        put:
            operationId: updateUser
            summary:
            description:
            parameters:
                - name: userId 
                    in: path
                    required: true
                    description: The ID of the user to update.
                    schema:
                        type:
                        format:
                        minimum:
            responses:
                "200":
                    description: User updated
                "401":
                    description: Authorization failed
                "404":
                    description:
                default:
                    description: Unexpected error
        delete:
            operationId: deleteUser
            summary:
            description:
            parameters:
                - name: userId 
                    in: path
                    required: true
                    description: The ID of the user to delete.
                    schema:
                        type:
                        format:
                        minimum:
            responses:
                "200":
                    description: User deleted
                "401":
                    description: Auth failed
                "404":
                    description: User not found
                "500":
                    description: Server error
                default:
                    description: Unexpected error
    /api/users/signup:
        post:
            operationId: addUser
            summary: Creates a user.
            description:
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type:
                            properties:
                                name:
                                    type: String
                                address:
                                    type: String
                                email:
                                    type: String
                                password:
                                    type: String
                                
            responses:
                "201":
                    description: User created
                "400":
                    description: User already exists
                "500":
                    description: Server error
                default:
                    description: Unexpected error
    /api/users/login:
        post:
            operationId: userLogin
            summary: Login user.
            description:
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type:
                            properties:
                                email:
                                    type: String
                                password:
                                    type: String
            responses:
                "200":
                    description: 
                "401":
                    description: Email or password is incorrect

    /api/users/logout:
        get:
            operationId: userLogout
            summary: Logout user.
            description:
            requestHeader:
                required: true
                content:
                    header: 
                        properties:
                            name: Authorization
                                type: String
            responses:
                "500":
                    description: Server error
                default:
                    description: Unexpected error
                      
